baseurl = "https://piggins.github.io/anmeldung-generator/"
languageCode = "en"
title = "Anmeldung in English"
theme = "Hucore"
copyright = "&copy; 2017"
googleAnalytics = "UA-96993711-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "The Anmeldung helper"
sharingicons = true
displayauthor = true
custom_css = ["css/custom.css", "css/bootstrap.css"]
