baseurl = "http://anmeldunginenglish.com"
languageCode = "en"
title = "Anmeldung in English"
theme = "Hucore"
copyright = "&copy; 2017 | <a href=\"/post/privacy-policy\" target=\"_blank\">Privacy Policy</a>"
googleAnalytics = "UA-96993711-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Generate the Anmeldung Form in English, and receive a completed Anmeldung PDF in German."
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "The Anmeldung helper"
sharingicons = false
displayauthor = false
custom_css = ["css/custom.css", "css/bootstrap.css"]
